---
title:               TestApp
tagline:             Clever tagline.
login:               <%= ENV["testapp_login"] ? ENV["testapp_login"] : "username" %>
password:            <%= ENV["testapp_password"] ? ENV["testapp_password"] : "password" %>
name:                Your name
twitter:             your_twitter_handle
github:              your_github_handle
email:               address@example.com
